---

- name: Add ammjmsroute stanza as per SRE-2240
  hosts: all_nagios
  tasks:
    - name: add stanzatext is added from ansible
      blockinfile:
        dest: /opt/splunkforwarder/etc/apps/ssn/local/inputs.conf
        block: |
                 #Added as per SRE-2240
                 [monitor:///usr/ssn/ammjmsroute/CURRENT/logs/gc.log]
                  sourcetype = server-ammjmsroute
                  index = ssn
        state: present
        insertafter: EOF
      become: True
      become_user: root
      register: found
