---
- name: Replacing the text in file
  hosts: test_nagios
  become: true
  become_user: root
  tasks:
  - name: Replace
    replace: dest=/home/rkondepu/weeks.txt regexp='Saturday' replace='Friday'
