---

- name: Add ssnagentforwarder stanza as per SRE-2231
  hosts: all_nagios
  tasks:
    - name: add stanzatext is added from ansible
      blockinfile:
        dest: /opt/splunkforwarder/etc/apps/ssn/local/inputs.conf
        block: |
                 #Added as per SRE-2231
                 [monitor:///usr/ssn/ssnagentforwarder/CURRENT/logs/gc.log]
                 sourcetype = server-ssnagentforwarder
                 index = ssn
        state: present
        insertafter: EOF
      become: True
      become_user: root
      register: found
